# Generated by Django 3.1.4 on 2020-12-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statid', models.CharField(blank=True, db_column='statId', max_length=8, null=True)),
                ('statnm', models.CharField(blank=True, db_column='statNm', max_length=100, null=True)),
                ('chgerid', models.CharField(blank=True, db_column='chgerId', max_length=2, null=True)),
                ('chgertype', models.CharField(blank=True, db_column='chgerType', max_length=2, null=True)),
                ('addr', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('lng', models.CharField(blank=True, max_length=20, null=True)),
                ('usetime', models.CharField(blank=True, db_column='useTime', max_length=50, null=True)),
                ('busiid', models.CharField(blank=True, db_column='busiId', max_length=2, null=True)),
                ('businm', models.CharField(blank=True, db_column='busiNm', max_length=50, null=True)),
                ('busicall', models.CharField(blank=True, db_column='busiCall', max_length=20, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
    ]
