# Generated by Django 3.1.4 on 2021-01-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ev_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNick', models.CharField(max_length=16)),
                ('contents', models.CharField(max_length=300)),
                ('statId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_api.stations')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
